FORMAT: 1A
HOST: http://apps.bxx.it/

# Bxx - Timesheet

## Projects Collection [/projects]
 
### List All Projects [GET]

+ Response 200 (application/json)

        [
            {
                "prjName": "Favourite programming language?",
                "prjNumber": "2015-08-05T08:40:51.620Z",
                "function": "",
                "prjType": "",
                "prdType": ""
            }
        ]

## Activities Collection [/activities{?userId}]

### Create Activity [POST]

+ Request (application/json)
    + Attributes(Activity)

+ Response 201


### Month activities [GET /activities/{month}]

+ Parameters
    + month: `Febbraio-2015` - formatted as `MMMM-YYYY`

+ Response 200 (application/json)
        
        [
            {
                "funct": "Other",
                "prjType": "Project 1",
                "prjNumber": "Project 1",
                "prjDescription": "Project xyz",
                "prdType": "Product 1",
                "dates": {
                    "1": 8,
                    "2": 4,
                    "3": 8,
                    "4": 4,
                    "5": 4,
                    "6": 4,
                    "7": 4,
                    "8": 8,
                    "9": 8,
                    "10": 8,
                    "11": 8,
                    "12": 4,
                    "13": 8,
                    "14": 4,
                    "15": 4,
                    "16": 4,
                    "17": 4,
                    "18": 8,
                    "19": 8,
                    "20": 8,
                    "21": 8,
                    "22": 4,
                    "23": 8,
                    "24": 4,
                    "25": 4,
                    "26": 4,
                    "27": 4,
                    "28": 8,
                    "29": 4,
                    "30": 8
                }
                },{
                "funct": "Other",
                "prjType": "Project 2",
                "prjNumber": "Project 2",
                "prjDescription": "Project xyz",
                "prdType": "Product 2",
                "dates": {
                    "1": 0,
                    "2": 4,
                    "3": 0,
                    "4": 4,
                    "5": 4,
                    "6": 4,
                    "7": 4,
                    "8": 0,
                    "9": 0,
                    "10": 0,
                    "11": 0,
                    "12": 4,
                    "13": 0,
                    "14": 4,
                    "15": 4,
                    "16": 4,
                    "17": 4,
                    "18": 0,
                    "19": 0,
                    "20": 0,
                    "21": 0,
                    "22": 4,
                    "23": 0,
                    "24": 4,
                    "25": 4,
                    "26": 4,
                    "27": 4,
                    "28": 0,
                    "29": 4,
                    "30": 0
                }
            }
        ]


## Activity [/activities/{id}]

+ Parameters
    + id

+ Attributes
    + prjNumber
    + id
    + userId
    + duration
    + date

### Read Activity [GET]

+ Response 200 (application/json)
    + Attributes(Activity)

### Update Activity [PUT]

+ Request (application/json)
    + Attributes(Activity)

+ Response 200 (application/json)
    + Attributes(Activity)

### Delete Activity [DELETE]

+ Response 204
