FORMAT: 1A
HOST: http://apps.bxx.it/

# Bxx - Timesheet

## Projects Collection [/projects]
 
### List All Projects [GET]

+ Response 200 (application/json)

        [
            {
                "prjDescription": "Favourite programming language?",
                "prjNumber": "5",
                "funct": "fn",
                "prjType": "type1",
                "prdType": "what"
            },
            {
                "prjDescription": "New project name",
                "prjNumber": "Project 2",
                "funct": "fn",
                "prjType": "type1",
                "prdType": "banana"
            }
        ]

## Activities Collection [/activities{?userId}]

### Create Activity [POST]

+ Request (application/json)
    + Attributes(Activity)

+ Response 201

    + Headers
    
        Location: /activities/1


## Month activities [/activities/month/{month}]

### Read Month Activities [GET]

+ Parameters
    + month: `Febbraio-2015` - formatted as `MMMM-YYYY`

+ Response 200 (application/json)
        
        [
            {
                "funct": "Other",
                "prjType": "Project 1",
                "prjNumber": "Project 1",
                "prjDescription": "Project xyz",
                "prdType": "Product 1",
                "activities": [
                    {
                        "id": 7,
                        "date": "20-12-2015",
                        "duration": 5
                    },
                    {
                        "id": 1,
                        "date": "21-12-2015",
                        "duration": 7
                    },
                    {
                        "id": 2,
                        "date": "22-12-2015",
                        "duration": 3
                    },
                    {
                        "id": 3,
                        "date": "23-12-2015",
                        "duration": 4
                    }
                ]
            },{
                "funct": "Other",
                "prjType": "Project 2",
                "prjNumber": "Project 2",
                "prjDescription": "Project xyz",
                "prdType": "Product 2",
                "activities": [
                    {
                        "id": 4,
                        "date": "23-12-2015",
                        "duration": 5
                    },
                    {
                        "id": 5,
                        "date": "21-12-2015",
                        "duration": 7
                    },
                    {
                        "id": 6,
                        "date": "22-12-2015",
                        "duration": 3
                    },
                    {
                        "id": 8,
                        "date": "12-12-2015",
                        "duration": 4
                    }
                ]
            }
        ]


## Activity [/activities/{id}]

+ Parameters
    + id: 1

+ Attributes
    + prjNumber
    + id
    + userId
    + duration
    + date

### Read Activity [GET]

+ Response 200 (application/json)
    + Attributes(Activity)

### Update Activity [PUT]

+ Request (application/json)
    + Attributes(Activity)

+ Response 200 (application/json)
    + Attributes(Activity)

### Delete Activity [DELETE]

+ Response 204
